name: Reusable workflow A

on:
  workflow_call:
    inputs:
      param1:
        description: 'Param1'
        required: true
        type: string

jobs:
  call-another-reusable:
    runs-on: ubuntu-latest
    env:
      secret_param1: ${{ secrets.param1 }}
    steps:
      - run: |
         echo ${{ inputs.param1 }}
         echo "masterka"
         echo $secret_param1
