name: Reusable workflow A

on:
  workflow_call:
    inputs:
      param1:
        description: 'Param1'
        required: true
        type: string
    secrets:
      param1:
        required: true


jobs:
  call-another-reusable:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo ${{ inputs.param1 }}
         echo "masterka"
         echo ${{ secrets.param1 }}
